--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/vgui/ttt/exho_martyrdom.png" )
	resource.AddFile( "materials/vgui/ttt/perks/martyrdom_perk_hud.png" )
	resource.AddFile( "sound/matyrdom/grenade_bounce.mp3" )
end